### ISSUE TITLE
Test files (txn_test_%d_%d.csv) seem to be missing

### ISSUE THREAD

**Issue by samvher** [MIT-DB-Class/go-db-2024#1]
[I am not an MIT student but following along as an outsider. I hope I'm being helpful flagging this, but feel free to ignore if I'm not.]

In `transaction_test.go` the code tries to load a CSV file:
```
	csvFile, err := os.Open(fmt.Sprintf("txn_test_%d_%d.csv", tupCnt, pgCnt))
```

This CSV doesn't seem to be checked into the repository. Maybe that's an oversight?

[Thanks _a lot_ for making these course materials public. It's been great so far!]

**Comment by svh-cb** [comment]
Looks like this is resolved, thank you!

**Comment by samvher** [comment]
Looks like this is resolved, thank you!
